baseURL = 'https://avb-academy.com/'
languageCode = 'en-us'
title = 'AVB Academy'
theme = 'hugo-theme-relearn'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  themeVariantAuto = ['zen-light', 'zen-dark']
  termbaseStrict = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'
    excludeFiles = ['**/*.drawio', '**/*.drawio.svg', '**/*.bkp', 'images/*.sh', 'build_scripts/']

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.de]
    languageName = "Deutsch"
    weight = 2
